export const EXP_REGULARES = {
    SOLO_DIGITOS: new RegExp(/^([0-9]){1}$/),
    SOLO_TEXTO: new RegExp(/^([\wáÁéÉíÍóÓúÚñÑüÜ]|\s){1}$/),
    ALPHANUMERIC : new RegExp(/^[a-z0-9]+$/i),
    LATIN_ALPHABET_AND_NUMERIC : new RegExp(/^[a-zA-Z0-9\sáÁéÉíÍóÓúÚñÑüÜ]+$/i),
    NUMERACION_VAL : new RegExp(/^[a-z\d\s\wáÁéÉíÍóÓúÚñÑüÜ\-]+$/i),
    SOLO_CARTAS : new RegExp( /^[a-zA-ZwáÁéÉíÍóÓúÚñÑüÜ\s]*$/),
    TEXTO_DIRECCIONES: new RegExp(/^([\wáÁéÉíÍóÓúÚñÑüÜ]|\s|\,|\.){1}$/),
    TEXTO_NOMBRES: new RegExp(/^([\wáÁéÉíÍóÓúÚñÑüÜ]|\s){1}$/),
    CARACTERES_CEDULA: new RegExp(/^\d{10}$/),
    CARACTERES_CONTRASENNA: new RegExp(/^(\d|[\+|\-|\!|\*|\@|\%|\$]|[A-Z]|[a-z]){0,1}$/),
    CARACTERES_FECHA: new RegExp(/^\d{0,1}\/{0,1}$/),
    CARACTERES_HUELLA: new RegExp(/^([a-zA-Z]|\d){0,1}$/),
    CARACTERES_MAIL: new RegExp(/^\w{0,1}[\|@|\-|\.|\_]{0,1}$/),
    EMAIL_PATTERN: new RegExp( /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/),
    VALOR_FINAL_CONTRASENNA: new RegExp(/^(?=.*\d)(?=.*[\+|\-|\!|\*|\@|\%|\$])(?=.*[A-Z])(?=.*[a-z])\S{8,16}$/),
    VALOR_FINAL_FECHA: new RegExp(/^[0-3]{1}\d{1}\/{1}[0-1]{1}\d{1}\/{1}\d{4}$/),
    VALOR_FINAL_HUELLA: new RegExp(/^[a-zA-Z]{1}\d{4}[a-zA-Z]{1}\d{0,4}$/),
    VALOR_FINAL_MAIL: new RegExp(/^(([^<>()[\]\.,;:\s@\"]+(\.[^<>()[\]\.,;:\s@\"]+)*)|(\".+\"))@(([^<>()[\]\.,;:\s@\"]+\.)+[^<>()[\]\.,;:\s@\"]{2,})$/),
    VALOR_FINAL_OTP: new RegExp(/^\d{6}$/),
    FECHA_FORMATO : new RegExp(/^\d{4}[\/.]\d{1,2}[\/.]\d{1,2}$/),
    // custom
    TWO_DECIMAL_POINT : new RegExp(/^\d*\.?\d{0,1}$/),
    DECIMAL_POINT : new RegExp(/^\d*\.?\d{0,2}$/),
    CELULAR_VAL : new RegExp(/^09\d{8}$/),
    TELEFONO_FIJO : new RegExp(/^0\d{8}$/),
    REGEXP_LETRAS_NUMEROS: new RegExp( /^[a-zA-Z0-9]*$/),
    REGEXP_LETRAS_NUMEROS_GUION: new RegExp( /^[a-zA-Z0-9-]*$/),
    REGEXP_CARACTERES_NOMBRE_APELLIDO_CIUDAD: new RegExp( /^[a-zA-ZñÑ ]*$/),
    REGEXP_CARACTERES_DIR_CALLE: new RegExp( /^[a-zA-ZñÑ0-9- ]*$/),
    NUMERO_BARA : new RegExp(/[0-9/]/),
    DOS_NOMBRES: new RegExp(/^([A-Za-zÁÉÍÓÚñáéíóúÑ]{0}?[A-Za-zÁÉÍÓÚñáéíóúÑ\']+[\s])+([A-Za-zÁÉÍÓÚñáéíóúÑ]{0}?[A-Za-zÁÉÍÓÚñáéíóúÑ\'])+[\s]?([A-Za-zÁÉÍÓÚñáéíóúÑ]{0}?[A-Za-zÁÉÍÓÚñáéíóúÑ\'])?$/),
    NOMBRE_EMPRESA : new RegExp(/^[a-zA-Z0-9\sáÁéÉíÍóÓúÚñÑüÜ&]+$/i),
    TREE_DECIMAL_POINT : new RegExp(/^\d*\.?\d{0,2}$/),
    ALPHANUMERIC_UNDERSCORE : new RegExp (/^[a-zA-Z0-9-_\sáÁéÉíÍóÓúÚñÑüÜ]+$/i),
    SOLO_NUMEROS:new RegExp (/[0-9][0-9]*$/)
  };
